### ISSUE TITLE
Exception: Switch did not start before timeout

### ISSUE THREAD

**Issue by WangchukSherpa** [reginalab/dh-aes-p4#3]
unable to Initiate the program switch not responding even after proper installation
![1](https://github.com/reginalab/dh-aes-p4/assets/95025561/d00aa8d8-d1dc-4c73-babd-7072cfd0492a)
![Screenshot from 2024-03-22 22-07-51](https://github.com/reginalab/dh-aes-p4/assets/95025561/481c2cea-a294-4396-a516-0896f1feb086)

**Comment by ramonfontes** [comment]
Please make sure you have all the p4 dependencies satisfied.

**Comment by emdneto** [comment]
Hi @WangchukSherpa 
Probably it's a issue with the path of the P4 json file inside mn_code.py. As @ramonfontes said, make sure you have the json files.
